version: '3.8'
services:
frontend:
build:
context: .
dockerfile: Dockerfile
container_name: flask_frontend
restart: unless-stopped
environment:
PORT: 5000
DEBUG: "False"
BACKEND_URL: ${BACKEND_URL}
SECRET_KEY: ${SECRET_KEY}
ports:
- "5000:5000"
networks:
- frontend_network
networks:
frontend_network:
driver: bridge